### ISSUE TITLE
Problem of changing to Stereo mode

### ISSUE THREAD

**Issue by striversist** [Waxo/ALSA_encapsulation#1]
Hi Waxo:

```
I built and run the program successfully. Thanks for your code.
But when I only change the param stereo_mode in AlsaControl constructor in main function to STEREO. The output wav is abnormal. The sound seems 2 times faster. 
Is there something wrong?

Waiting for your answer, thanks.
```

**Comment by Waxo** [comment]
Hi, thank you for your feedback, I may have made a mistake for the stereo mode, anyway the code is unclear and i plan to refactor it. And improve some methods.

For your problem i think about two possible problems :
- I use the `snd_pcm_readi` maybe using the `snd_pcm_readn` may be better. [Alsa Documentation](http://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html)
- When i write the sound in a file i do `rc * 2`, this calculation may be wrong

**Comment by Waxo** [comment]
Last commit fix the problem, the writing size was wrong for STEREO mode.
